language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master

notifications:
  email: false

git:
  submodules: false

before_install:
  sudo apt-get install libx11-dev
  # Prepare compilers
  - if [ "$CXX" = "g++" ]; then
      sudo apt-get install g++-4.8 -qq;
      export CXX="g++-4.8" CC="gcc-4.8";
    fi
  - if [ "$CXX" = "clang++" ]; then
      sudo apt-get install libstdc++-4.8-dev;
    fi

before_script:
  - cmake -DTARGET_LINUX=ON .

script:
  - make -j 4
