language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libglew-dev
  - if [ "$CXX" = "g++" ]; then
      sudo apt-get install g++-4.8 -qq;
      export CXX="g++-4.8" CC="gcc-4.8";
    fi
  - if [ "$CXX" = "clang++" ]; then
      sudo apt-get install libstdc++-4.8-dev;
    fi

before_script:
  - cmake .

script:
  - make -j 4
